name: Print the list of commits and users in a pull request

on: 
  push
    
jobs:
  print-push-details:

    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
      - name: print username
        run: git log --format='%an'
      - name: print pull request details
        run: git log --format= "pull-request-description"